services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.frontend
    ports:
      - "8080:80"

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.backend