# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: kemechial/nasa-api-backend:v1
        ports:
         - containerPort: 3030
        env:
        - name: NASA_API_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: NASA_API_KEY

---

# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: kemechial/nasa-api-frontend:v1
        ports:
        - containerPort: 80

